//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public decimal CusID { get; set; }
        public decimal OrderID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ShippingAndHandling { get; set; }
        public decimal tax { get; set; }
        public decimal Total { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
    }
}
