//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public decimal CusID { get; set; }
        public string Fullname { get; set; }
        public decimal Mobilephone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual BillAddressTable BillAddressTable { get; set; }
        public virtual CartTable CartTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
