//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public decimal CusID { get; set; }
        public decimal OrderId { get; set; }
        public decimal Subtotal { get; set; }
        public decimal ShippingAndHandling { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
    }
}
