//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public decimal index { get; set; }
        public decimal subtotal { get; set; }
        public decimal shipping { get; set; }
        public decimal tax { get; set; }
        public decimal totalamt { get; set; }
    }
}
